// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 卡片边关系缓存（与 Go 后端 CardEdge 对齐）
 */
export type CachedEdge = { source_id: string, target_id: string, relation: string, };

/**
 * 卡片布局缓存记录（与 Go 后端 CardLayout + CardMetrics 对齐）
 */
export type CachedLayout = { card_id: string, x: number, y: number, title: string, category_id: string | null, hot_score: number, updated_at: string, };

/**
 * A single configuration issue detected by the scanner
 */
export type ConfigIssue = { 
/**
 * e.g., "S3_ACCESS_KEY", "WS_URL"
 */
field: string, 
/**
 * Severity level
 */
severity: IssueSeverity, 
/**
 * Human-readable description
 */
message: string, 
/**
 * How to fix, e.g., "Open Settings > Storage"
 */
fix_hint: string, };

/**
 * 草稿数据传输对象（返回给前端）
 */
export type DraftDto = { card_id: string, raw_md: string, ast_data: string | null, updated_at: number, };

/**
 * 导出结果摘要
 */
export type ExportSummaryDto = { total_cards: number, total_images: number, zip_size_bytes: number, };

/**
 * 文件变更事件（传递给前端）
 */
export type FileChangeEvent = { path: string, kind: string, timestamp: string, };

/**
 * Impact on a single file
 */
export type FileImpact = { 
/**
 * File path
 */
path: string, 
/**
 * Number of wikilinks in this file
 */
link_count: number, };

/**
 * 上传结果，返回给前端
 */
export type ImageUploadResult = { 
/**
 * S3 对象 key（相对路径）
 */
key: string, 
/**
 * CDN 公开访问 URL
 */
url: string, 
/**
 * 压缩后的文件大小（字节）
 */
size_bytes: number, 
/**
 * 原始文件大小（字节）
 */
original_size_bytes: number, };

/**
 * Severity level for configuration issues
 */
export type IssueSeverity = "Critical" | "Warning" | "Info";

/**
 * 本地布局缓存查询结果
 */
export type LayoutCacheResult = { layouts: Array<CachedLayout>, edges: Array<CachedEdge>, count: number, last_sync: string | null, };

/**
 * 前端拿到的登录结果
 */
export type LoginResult = { user_id: string, username: string, role: string, };

/**
 * Result of previewing a merge operation
 */
export type MergePreview = { 
/**
 * Number of files that will be modified
 */
files_to_modify: number, 
/**
 * Total number of wikilinks to be replaced
 */
total_wikilinks: number, 
/**
 * Details of each affected file
 */
affected_files: Array<FileImpact>, };

/**
 * Markdown 渲染结果，返回给前端
 */
export type RenderResult = { 
/**
 * 渲染后的 HTML 字符串
 */
html: string, 
/**
 * AST 结构化 JSON 字符串
 */
ast_json: string, 
/**
 * 从原文提取的纯文本摘要
 */
excerpt: string, 
/**
 * 从原文提取的 wikilink 链接（提取自 Markdown 的链接目标）
 */
extracted_links: Array<string>, };

/**
 * Result of scanning configuration
 */
export type ScanResult = { 
/**
 * List of detected issues
 */
issues: Array<ConfigIssue>, 
/**
 * true if no Critical issues
 */
is_healthy: boolean, };

/**
 * 服务端同步操作结果
 */
export type SyncResult = { success: boolean, message: string, synced_count: number, };

export type SysConfig = { api_base_url: string, ws_url: string, s3_endpoint: string, s3_region: string, s3_bucket: string, s3_access_key: string | null, s3_secret_key: string | null, s3_public_url_base: string | null, s3_use_path_style: boolean, vault_path: string | null, };

/**
 * 目录树节点（直接复用 crate 的结构，增加 Serialize）
 *
 * 前端可用于渲染侧边栏目录导航。
 */
export type TocNodeDto = { level: number, text: string, slug: string, children: Array<TocNodeDto>, };
